name: flutter_local_storages
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_riverpod: ^2.4.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.0
  # Isar
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Objectbox
  objectbox: ^2.3.1
  objectbox_flutter_libs: ^2.3.1
  # Sembast
  sembast: ^3.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  pretty_dio_logger: ^1.3.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  # Isar
  isar_generator: ^3.1.0+1
  # Hive
  hive_generator: ^2.0.1
  # Objectbox
  objectbox_generator: ^2.3.1

flutter:
  uses-material-design: true
